# Generated by Django 5.2.6 on 2025-09-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('technology', models.CharField(choices=[('python', 'Python'), ('.net', '.NET'), ('java', 'Java'), ('react', 'React')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('time_limit', models.IntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
