# Generated by Django 5.2.6 on 2025-09-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_candidate_questionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.question'),
        ),
    ]
