# Generated by Django 5.2.6 on 2025-09-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_questionanswer_answer_text_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='questionanswer',
        #     name='candidate',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.candidate'),
        # ),
    ]
