# Generated by Django 5.2.6 on 2025-09-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_questionanswer_candidate'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='questionanswer',
        #     name='ai_response',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='questionanswer',
        #     name='rating',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
    ]
