# Generated by Django 5.2.8 on 2025-12-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_questionanswer_ai_response_questionanswer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_quick',
            field=models.BooleanField(default=False),
        ),
    ]
