# Generated by Django 5.2.8 on 2025-12-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_question_options_question_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='q_ans_file',
            field=models.FileField(blank=True, null=True, upload_to='question-answer/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='snapshots',
            field=models.FileField(blank=True, null=True, upload_to='snapshorts/'),
        ),
    ]
