# Generated by Django 5.2.8 on 2025-12-17 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_questionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
